[FIX] account_payment_sale: Not set the product_uom field in the sales order lines
If sale_variant_configurator is installed we will have an error about it, so it is better not to set it explicitly.

File "/opt/odoo/auto/addons/account_payment_sale/tests/test_sale_order.py", line 25, in create_sale_order
    order_line.product_uom = p.uom_id
File "/opt/odoo/custom/src/odoo/odoo/tests/common.py", line 2355, in __setattr__
    assert not self._get_modifier(field, 'invisible'), \
AssertionError: can't write on invisible field product_uom